// Code generated by protoc-gen-go.
// source: POGOProtos/Networking/Envelopes/Unknown6.proto
// DO NOT EDIT!

/*
Package POGOProtos_Networking_Envelopes is a generated protocol buffer package.

It is generated from these files:
	POGOProtos/Networking/Envelopes/Unknown6.proto

It has these top-level messages:
	Unknown6
*/
package envelopes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Unknown6 struct {
	Unknown1 int32              `protobuf:"varint,1,opt,name=unknown1" json:"unknown1,omitempty"`
	Unknown2 *Unknown6_Unknown2 `protobuf:"bytes,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *Unknown6) Reset()                    { *m = Unknown6{} }
func (m *Unknown6) String() string            { return proto.CompactTextString(m) }
func (*Unknown6) ProtoMessage()               {}
func (*Unknown6) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Unknown6) GetUnknown2() *Unknown6_Unknown2 {
	if m != nil {
		return m.Unknown2
	}
	return nil
}

type Unknown6_Unknown2 struct {
	Unknown1 []byte `protobuf:"bytes,1,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
}

func (m *Unknown6_Unknown2) Reset()                    { *m = Unknown6_Unknown2{} }
func (m *Unknown6_Unknown2) String() string            { return proto.CompactTextString(m) }
func (*Unknown6_Unknown2) ProtoMessage()               {}
func (*Unknown6_Unknown2) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 0} }

func init() {
	proto.RegisterType((*Unknown6)(nil), "POGOProtos.Networking.Envelopes.Unknown6")
	proto.RegisterType((*Unknown6_Unknown2)(nil), "POGOProtos.Networking.Envelopes.Unknown6.Unknown2")
}

func init() { proto.RegisterFile("POGOProtos/Networking/Envelopes/Unknown6.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x0b, 0xf0, 0x77, 0xf7,
	0x0f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0xf7, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0xce, 0xcc,
	0x4b, 0xd7, 0x77, 0xcd, 0x2b, 0x4b, 0xcd, 0xc9, 0x2f, 0x48, 0x2d, 0xd6, 0x0f, 0xcd, 0xcb, 0xce,
	0xcb, 0x2f, 0xcf, 0x33, 0xd3, 0x2b, 0x00, 0x29, 0x12, 0x92, 0x47, 0xa8, 0xd7, 0x43, 0xa8, 0xd7,
	0x83, 0xab, 0x57, 0x9a, 0xc7, 0xc8, 0xc5, 0x01, 0xd3, 0x23, 0x24, 0xc5, 0xc5, 0x51, 0x0a, 0x61,
	0x1b, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x42, 0x7e, 0x70, 0x39, 0x23, 0x09,
	0x26, 0xa0, 0x1c, 0xb7, 0x91, 0x91, 0x1e, 0x01, 0xc3, 0xf5, 0xe0, 0x8e, 0x81, 0x32, 0x8c, 0xe0,
	0xe6, 0x19, 0x49, 0xa9, 0xc1, 0xed, 0x35, 0xc2, 0xb0, 0x97, 0x07, 0x61, 0x6f, 0x12, 0x1b, 0xd8,
	0x23, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x23, 0x6d, 0x9f, 0xfa, 0x00, 0x00, 0x00,
}
